# Site settings
title: VEC Club is one of the big clubs in Chennai.
tag_text: MozillaTN @ VEC


baseurl: /
domain_name: 'http://mozillatn.github.io'
google_analytics: 'UA-63310670-1'
disqus: true
disqus_shortname: 'MozillaTN'
permalink:      /:title/

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed


defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

